name: disqam
description: Panduan tidur dan program DISQAM untuk lansia.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  excel: ^4.0.6
  file_saver: ^0.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^11.1.0
  http: ^1.6.0
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/materials/
